export const formData = [
  {
    "key": "firstname",
    "label": "Please Enter First Name",
    "formtype": "input",
    "valuetype": "string",
    "placeholder": "Please Enter your first name",
    "order":"0",
    "defaultValue": "",
    "options": "",
    "appearance": "outline",
      "icon": "person",
      "iconLocation": "after",
      "matformfield":"true",
      "hint": "add your name...",
      "required":"Yes",
      "error": "This is a new error message"
  },
  {
    "key": "lastname",
    "label": "Please Enter Last Name",
    "formtype": "textarea",
     "valuetype": "string",
    "defaultValue": "",
    "placeholder": "Please Enter your last name",
    "order":"1",
    "options": "",
    "appearance": "outline",
    "icon": "person",
    "iconLocation": "after",
    "matformfield":"true",
    "hint": "",
    "required":"No",
    "error": "This is a new error message"
  },
  {
    "key": "sex",
    "label": "Please select a sex",
    "formtype": "select",
    "valuetype": "array",
    "defaultValue": "",
    "placeholder": "Please select a sex",
    "order":"2",
    "options": ["Male", "Female"],
    "appearance": "fill",
    "icon": "person",
    "iconLocation": "after",
    "matformfield":"true",
    "hint": "",
    "required":"Yes",
    "error": "This is a new error message"
  },
  {
    "key": "details",
    "label": "Details of Incident",
    "formtype": "textarea",
    "valuetype": "string",
    "defaultValue": "",
    "placeholder": "Please provide some details of incident",
    "order":"3",
    "options": "",
    "appearance": "standard",
      "icon": "",
      "iconLocation": "",
      "matformfield":"true",
      "hint": "",
      "required":"Yes",
      "error": "This is a new error message"
  },
  {
    "key": "country",
    "label": "Please select a country",
    "formtype": "select",
    "valuetype": "array",
    "defaultValue": "",
    "placeholder": "Please select a country",
    "order":"4",
    "options": ["Wales","Scotland", "Ireland", "England"],
    "appearance": "fill",
      "icon": "location",
      "iconLocation": "after",
      "matformfield":"true",
      "hint": "",
      "required":"No",
      "error": "This is a new error message"
  },
  {
    "key": "fault",
    "label": "When was the event",
    "formtype": "date",
    "valuetype": "date",
    "defaultValue": "",
    "placeholder": "Please select a date",
    "order":"5",
    "options": "",
    "appearance": "outline",
      "icon": "",
      "iconLocation": "",
      "matformfield":"true",
      "hint": "",
      "required":"Yes",
      "error": "This is a new error message"
  },
  {
    "key": "radios",
    "label": "Chose one",
    "formtype": "radio",
    "valuetype": "array",
    "defaultValue": "",
    "placeholder": "Please chose radio option",
    "order":"6",
    "options": ["radio one","radio two","radio three"],
    "appearance": "outline",
      "icon": "",
      "iconLocation": "",
      "matformfield":"false",
      "hint": "",
      "required":"No",
      "error": "This is a new error message"
  }
  ,
  {
    "key": "checkboes",
    "label": "Chose at least one",
    "formtype": "checkbox",
    "valuetype": "array",
    "defaultValue": "",
    "placeholder": "Please chose checkboxes",
    "order":"7",
    "options": ["box one","box two","box three"],
    "appearance": "outline",
      "icon": "",
      "iconLocation": "",
      "matformfield":"false",
      "hint": "",
      "required":"No",
      "error": "This is a new error message"
  },
  {
    "key": "button",
    "label": "Submit Button",
    "formtype": "button",
    "valuetype": "",
    "defaultValue": "",
    "placeholder": "Please chose checkboxes",
    "order":"7",
    "options": "testFunc",
    "appearance": "primary",
      "icon": "",
      "iconLocation": "",
      "matformfield":"false",
      "hint": "",
      "required":"No",
      "error": "This is a new error message"
  }
]


